/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_wnd (void)
{
  GtkWidget *wnd;
  GtkWidget *vbox;
  GtkWidget *menubar1;
  GtkWidget *menuitem1;
  GtkWidget *menu1;
  GtkWidget *new1;
  GtkWidget *open1;
  GtkWidget *save1;
  GtkWidget *save_as1;
  GtkWidget *separatormenuitem1;
  GtkWidget *quit1;
  GtkWidget *menuitem2;
  GtkWidget *menu2;
  GtkWidget *cut1;
  GtkWidget *copy1;
  GtkWidget *paste1;
  GtkWidget *delete1;
  GtkWidget *menuitem3;
  GtkWidget *menu3;
  GtkWidget *menuitem4;
  GtkWidget *menu4;
  GtkWidget *about1;
  GtkWidget *toolbar;
  GtkIconSize tmp_toolbar_icon_size;
  GtkWidget *tmp_image;
  GtkWidget *tb_start;
  GtkWidget *separatortoolitem1;
  GtkWidget *tb_stop;
  GtkWidget *vp_1st;
  GtkWidget *vp_2nd;
  GtkWidget *vp_3rd;
  GtkWidget *sw_1st;
  GtkWidget *treeview_1st;
  GtkWidget *sw_2nd;
  GtkWidget *treeview_2nd;
  GtkWidget *sw_3rd;
  GtkWidget *treeview_3rd;
  GtkWidget *sw_4th;
  GtkWidget *textview;
  GtkWidget *statusbar;
  GtkAccelGroup *accel_group;

  accel_group = gtk_accel_group_new ();

  wnd = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (wnd), _("Sniffer on Switch"));

  vbox = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox);
  gtk_container_add (GTK_CONTAINER (wnd), vbox);

  menubar1 = gtk_menu_bar_new ();
  gtk_widget_show (menubar1);
  gtk_box_pack_start (GTK_BOX (vbox), menubar1, FALSE, FALSE, 0);

  menuitem1 = gtk_menu_item_new_with_mnemonic (_("_File"));
  gtk_widget_show (menuitem1);
  gtk_container_add (GTK_CONTAINER (menubar1), menuitem1);

  menu1 = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (menuitem1), menu1);

  new1 = gtk_image_menu_item_new_from_stock ("gtk-new", accel_group);
  gtk_widget_show (new1);
  gtk_container_add (GTK_CONTAINER (menu1), new1);

  open1 = gtk_image_menu_item_new_from_stock ("gtk-open", accel_group);
  gtk_widget_show (open1);
  gtk_container_add (GTK_CONTAINER (menu1), open1);

  save1 = gtk_image_menu_item_new_from_stock ("gtk-save", accel_group);
  gtk_widget_show (save1);
  gtk_container_add (GTK_CONTAINER (menu1), save1);

  save_as1 = gtk_image_menu_item_new_from_stock ("gtk-save-as", accel_group);
  gtk_widget_show (save_as1);
  gtk_container_add (GTK_CONTAINER (menu1), save_as1);

  separatormenuitem1 = gtk_separator_menu_item_new ();
  gtk_widget_show (separatormenuitem1);
  gtk_container_add (GTK_CONTAINER (menu1), separatormenuitem1);
  gtk_widget_set_sensitive (separatormenuitem1, FALSE);

  quit1 = gtk_image_menu_item_new_from_stock ("gtk-quit", accel_group);
  gtk_widget_show (quit1);
  gtk_container_add (GTK_CONTAINER (menu1), quit1);

  menuitem2 = gtk_menu_item_new_with_mnemonic (_("_Edit"));
  gtk_widget_show (menuitem2);
  gtk_container_add (GTK_CONTAINER (menubar1), menuitem2);

  menu2 = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (menuitem2), menu2);

  cut1 = gtk_image_menu_item_new_from_stock ("gtk-cut", accel_group);
  gtk_widget_show (cut1);
  gtk_container_add (GTK_CONTAINER (menu2), cut1);

  copy1 = gtk_image_menu_item_new_from_stock ("gtk-copy", accel_group);
  gtk_widget_show (copy1);
  gtk_container_add (GTK_CONTAINER (menu2), copy1);

  paste1 = gtk_image_menu_item_new_from_stock ("gtk-paste", accel_group);
  gtk_widget_show (paste1);
  gtk_container_add (GTK_CONTAINER (menu2), paste1);

  delete1 = gtk_image_menu_item_new_from_stock ("gtk-delete", accel_group);
  gtk_widget_show (delete1);
  gtk_container_add (GTK_CONTAINER (menu2), delete1);

  menuitem3 = gtk_menu_item_new_with_mnemonic (_("_View"));
  gtk_widget_show (menuitem3);
  gtk_container_add (GTK_CONTAINER (menubar1), menuitem3);

  menu3 = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (menuitem3), menu3);

  menuitem4 = gtk_menu_item_new_with_mnemonic (_("_Help"));
  gtk_widget_show (menuitem4);
  gtk_container_add (GTK_CONTAINER (menubar1), menuitem4);

  menu4 = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (menuitem4), menu4);

  about1 = gtk_menu_item_new_with_mnemonic (_("_About"));
  gtk_widget_show (about1);
  gtk_container_add (GTK_CONTAINER (menu4), about1);

  toolbar = gtk_toolbar_new ();
  gtk_widget_show (toolbar);
  gtk_box_pack_start (GTK_BOX (vbox), toolbar, FALSE, FALSE, 0);
  gtk_toolbar_set_style (GTK_TOOLBAR (toolbar), GTK_TOOLBAR_BOTH);
  tmp_toolbar_icon_size = gtk_toolbar_get_icon_size (GTK_TOOLBAR (toolbar));

  tmp_image = gtk_image_new_from_stock ("gtk-media-play", tmp_toolbar_icon_size);
  gtk_widget_show (tmp_image);
  tb_start = (GtkWidget*) gtk_tool_button_new (tmp_image, _("Start"));
  gtk_widget_show (tb_start);
  gtk_container_add (GTK_CONTAINER (toolbar), tb_start);

  separatortoolitem1 = (GtkWidget*) gtk_separator_tool_item_new ();
  gtk_widget_show (separatortoolitem1);
  gtk_container_add (GTK_CONTAINER (toolbar), separatortoolitem1);

  tmp_image = gtk_image_new_from_stock ("gtk-stop", tmp_toolbar_icon_size);
  gtk_widget_show (tmp_image);
  tb_stop = (GtkWidget*) gtk_tool_button_new (tmp_image, _("Stop"));
  gtk_widget_show (tb_stop);
  gtk_container_add (GTK_CONTAINER (toolbar), tb_stop);

  vp_1st = gtk_vpaned_new ();
  gtk_widget_show (vp_1st);
  gtk_box_pack_start (GTK_BOX (vbox), vp_1st, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (vp_1st), 1);

  vp_2nd = gtk_vpaned_new ();
  gtk_widget_show (vp_2nd);
  gtk_paned_pack1 (GTK_PANED (vp_1st), vp_2nd, FALSE, TRUE);

  vp_3rd = gtk_vpaned_new ();
  gtk_widget_show (vp_3rd);
  gtk_paned_pack1 (GTK_PANED (vp_2nd), vp_3rd, FALSE, TRUE);

  sw_1st = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (sw_1st);
  gtk_paned_pack1 (GTK_PANED (vp_3rd), sw_1st, FALSE, TRUE);
  gtk_widget_set_size_request (sw_1st, 1000, 100);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (sw_1st), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (sw_1st), GTK_SHADOW_IN);

  treeview_1st = gtk_tree_view_new ();
  gtk_widget_show (treeview_1st);
  gtk_container_add (GTK_CONTAINER (sw_1st), treeview_1st);

  sw_2nd = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (sw_2nd);
  gtk_paned_pack2 (GTK_PANED (vp_3rd), sw_2nd, TRUE, TRUE);
  gtk_widget_set_size_request (sw_2nd, 1000, 150);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (sw_2nd), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (sw_2nd), GTK_SHADOW_IN);

  treeview_2nd = gtk_tree_view_new ();
  gtk_widget_show (treeview_2nd);
  gtk_container_add (GTK_CONTAINER (sw_2nd), treeview_2nd);

  sw_3rd = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (sw_3rd);
  gtk_paned_pack2 (GTK_PANED (vp_2nd), sw_3rd, TRUE, TRUE);
  gtk_widget_set_size_request (sw_3rd, 1000, 150);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (sw_3rd), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (sw_3rd), GTK_SHADOW_IN);

  treeview_3rd = gtk_tree_view_new ();
  gtk_widget_show (treeview_3rd);
  gtk_container_add (GTK_CONTAINER (sw_3rd), treeview_3rd);

  sw_4th = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (sw_4th);
  gtk_paned_pack2 (GTK_PANED (vp_1st), sw_4th, TRUE, TRUE);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (sw_4th), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (sw_4th), GTK_SHADOW_IN);

  textview = gtk_text_view_new ();
  gtk_widget_show (textview);
  gtk_container_add (GTK_CONTAINER (sw_4th), textview);
  
  // mark_set signal
  GtkTextBuffer * buffer;
  buffer = gtk_text_view_get_buffer (GTK_TEXT_VIEW (textview));
  gtk_text_buffer_create_tag(buffer, "tag", "background", "#6699cc", "foreground","#ffffff", NULL);
  g_signal_connect_object(buffer, "mark_set", G_CALLBACK(mark_set_callback), (gpointer)textview, 0);

  statusbar = gtk_statusbar_new ();
  gtk_widget_show (statusbar);
  gtk_box_pack_start (GTK_BOX (vbox), statusbar, FALSE, FALSE, 0);
  gtk_widget_set_size_request (statusbar, 4, 21);
  
  //
  g_object_set_data_full(G_OBJECT(treeview_2nd), "flag", (gpointer)TRUE, NULL);

  // set font
  PangoFontDescription *font = pango_font_description_from_string("Monospace");
  pango_font_description_set_size (font, 10 * PANGO_SCALE);
  gtk_widget_modify_font (treeview_1st, font);
  gtk_widget_modify_font (treeview_2nd, font);
  gtk_widget_modify_font (treeview_3rd, font);
  gtk_widget_modify_font (textview, font);

  g_signal_connect ((gpointer) wnd, "destroy",
                    G_CALLBACK (gtk_main_quit),
                    NULL);
  g_signal_connect ((gpointer) new1, "activate",
                    G_CALLBACK (on_new1_activate),
                    NULL);
  g_signal_connect ((gpointer) open1, "activate",
                    G_CALLBACK (on_open1_activate),
                    NULL);
  g_signal_connect ((gpointer) save1, "activate",
                    G_CALLBACK (on_save1_activate),
                    NULL);
  g_signal_connect ((gpointer) save_as1, "activate",
                    G_CALLBACK (on_save_as1_activate),
                    NULL);
  g_signal_connect ((gpointer) quit1, "activate",
                    G_CALLBACK (on_quit1_activate),
                    NULL);
  g_signal_connect ((gpointer) cut1, "activate",
                    G_CALLBACK (on_cut1_activate),
                    NULL);
  g_signal_connect ((gpointer) copy1, "activate",
                    G_CALLBACK (on_copy1_activate),
                    NULL);
  g_signal_connect ((gpointer) paste1, "activate",
                    G_CALLBACK (on_paste1_activate),
                    NULL);
  g_signal_connect ((gpointer) delete1, "activate",
                    G_CALLBACK (on_delete1_activate),
                    NULL);
  g_signal_connect ((gpointer) about1, "activate",
                    G_CALLBACK (on_about1_activate),
                    NULL);
  g_signal_connect ((gpointer) tb_start, "clicked",
                    G_CALLBACK (on_tb_start_clicked),
                    NULL);
  g_signal_connect ((gpointer) tb_stop, "clicked",
                    G_CALLBACK (on_tb_stop_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (wnd, wnd, "wnd");
  GLADE_HOOKUP_OBJECT (wnd, vbox, "vbox");
  GLADE_HOOKUP_OBJECT (wnd, menubar1, "menubar1");
  GLADE_HOOKUP_OBJECT (wnd, menuitem1, "menuitem1");
  GLADE_HOOKUP_OBJECT (wnd, menu1, "menu1");
  GLADE_HOOKUP_OBJECT (wnd, new1, "new1");
  GLADE_HOOKUP_OBJECT (wnd, open1, "open1");
  GLADE_HOOKUP_OBJECT (wnd, save1, "save1");
  GLADE_HOOKUP_OBJECT (wnd, save_as1, "save_as1");
  GLADE_HOOKUP_OBJECT (wnd, separatormenuitem1, "separatormenuitem1");
  GLADE_HOOKUP_OBJECT (wnd, quit1, "quit1");
  GLADE_HOOKUP_OBJECT (wnd, menuitem2, "menuitem2");
  GLADE_HOOKUP_OBJECT (wnd, menu2, "menu2");
  GLADE_HOOKUP_OBJECT (wnd, cut1, "cut1");
  GLADE_HOOKUP_OBJECT (wnd, copy1, "copy1");
  GLADE_HOOKUP_OBJECT (wnd, paste1, "paste1");
  GLADE_HOOKUP_OBJECT (wnd, delete1, "delete1");
  GLADE_HOOKUP_OBJECT (wnd, menuitem3, "menuitem3");
  GLADE_HOOKUP_OBJECT (wnd, menu3, "menu3");
  GLADE_HOOKUP_OBJECT (wnd, menuitem4, "menuitem4");
  GLADE_HOOKUP_OBJECT (wnd, menu4, "menu4");
  GLADE_HOOKUP_OBJECT (wnd, about1, "about1");
  GLADE_HOOKUP_OBJECT (wnd, toolbar, "toolbar");
  GLADE_HOOKUP_OBJECT (wnd, tb_start, "tb_start");
  GLADE_HOOKUP_OBJECT (wnd, separatortoolitem1, "separatortoolitem1");
  GLADE_HOOKUP_OBJECT (wnd, tb_stop, "tb_stop");
  GLADE_HOOKUP_OBJECT (wnd, vp_1st, "vp_1st");
  GLADE_HOOKUP_OBJECT (wnd, vp_2nd, "vp_2nd");
  GLADE_HOOKUP_OBJECT (wnd, vp_3rd, "vp_3rd");
  GLADE_HOOKUP_OBJECT (wnd, sw_1st, "sw_1st");
  GLADE_HOOKUP_OBJECT (wnd, treeview_1st, "treeview_1st");
  GLADE_HOOKUP_OBJECT (wnd, sw_2nd, "sw_2nd");
  GLADE_HOOKUP_OBJECT (wnd, treeview_2nd, "treeview_2nd");
  GLADE_HOOKUP_OBJECT (wnd, sw_3rd, "sw_3rd");
  GLADE_HOOKUP_OBJECT (wnd, treeview_3rd, "treeview_3rd");
  GLADE_HOOKUP_OBJECT (wnd, sw_4th, "sw_4th");
  GLADE_HOOKUP_OBJECT (wnd, textview, "textview");
  GLADE_HOOKUP_OBJECT (wnd, statusbar, "statusbar");

  gtk_window_add_accel_group (GTK_WINDOW (wnd), accel_group);
  
  pthread_t tid;
  pthread_create(&tid, NULL, show_hosts, (void *)treeview_1st);

  return wnd;
}

